import type { BuildingId } from './gameTypes';
import type { TileKey, TileVariant } from './cityMap';

export const labels: Record<TileKey, string> = {
  shop: 'Магазин',
  lot: 'Пусто',
  park: 'Парк',
  home: 'Дом',
  road: 'Дорога',
  school: 'Школа',
  water: 'Река',
  hospital: 'Больница',
  police: 'Полиция',
  fire: 'Пожарная',
  mall: 'ТЦ',
  factory: 'Завод',
  airport: 'Аэропорт',
  station: 'Вокзал',
  military: 'Военная база',
  stadium: 'Стадион',
  university: 'Университет',
  bank: 'Банк',
  port: 'Порт',
  museum: 'Музей',
};

export const variants: Record<TileKey, TileVariant> = {
  shop: 'work',
  lot: 'lot',
  park: 'nature',
  home: 'home',
  road: 'road',
  school: 'service',
  water: 'water',
  hospital: 'service',
  police: 'service',
  fire: 'service',
  mall: 'work',
  factory: 'work',
  airport: 'work',
  station: 'work',
  military: 'service',
  stadium: 'work',
  university: 'service',
  bank: 'work',
  port: 'work',
  museum: 'service',
};

export const buildingMap: Record<Exclude<TileKey, 'lot' | 'road' | 'water'>, BuildingId> = {
  shop: 'shops',
  park: 'parks',
  home: 'homes',
  school: 'schools',
  hospital: 'hospitals',
  police: 'police',
  fire: 'fireStations',
  mall: 'malls',
  factory: 'factories',
  airport: 'airports',
  station: 'stations',
  military: 'militaryBases',
  stadium: 'stadiums',
  university: 'universities',
  bank: 'banks',
  port: 'ports',
  museum: 'museums',
};

export const modelByBuilding: Record<BuildingId, TileKey> = {
  shops: 'shop',
  homes: 'home',
  schools: 'school',
  hospitals: 'hospital',
  police: 'police',
  fireStations: 'fire',
  parks: 'park',
  factories: 'factory',
  malls: 'mall',
  airports: 'airport',
  stations: 'station',
  militaryBases: 'military',
  stadiums: 'stadium',
  universities: 'university',
  banks: 'bank',
  ports: 'port',
  museums: 'museum',
};
